server:
  port: ${PORT:8080}

spring:
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true ## n para aplicacao caso de erro
    platform: postgresql ## plataforma q ta rodando
    maxActive: 3 ## maximo de conexoes ativas
  jpa:
    hibernate:
      ddl-auto: create-drop ## create-drop: toda vez que inicializa dropa 
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        