server:
  port: ${PORT:8080}

spring:

  main: 
    allow-bean-definition-overriding: true ##spring permite criar bean de um servi√ßo interno do proprio spring

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true ## n para aplicacao caso de erro
    platform: postgresql ## plataforma q ta rodando
    maxActive: 3 ## maximo de conexoes ativas
  jpa:
    hibernate:
      ddl-auto: create-drop ## create-drop: toda vez que inicializa dropa 
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672} ## curso falou 5672
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldjEyMzQ1Ng==}
  
  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue

  